### ISSUE TITLE
install.sh error in ubuntu 20.04

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#8]
ubuntu@VM-0-2-ubuntu:~$ wget https://github.com/matrixorigin/mo_ctl_standalone/blob/main/install.sh && bash +x install.sh
--2023-07-05 15:02:17--  https://github.com/matrixorigin/mo_ctl_standalone/blob/main/install.sh
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘install.sh’

install.sh                           [  <=>                                                   ] 179.30K   364KB/s    in 0.5s    

2023-07-05 15:02:18 (364 KB/s) - ‘install.sh’ saved [183605]

install.sh: line 8: syntax error near unexpected token `newline'
install.sh: line 8: `<!DOCTYPE html>'
ubuntu@VM-0-2-ubuntu:~$ sudo bash +x install.sh 
install.sh: line 8: syntax error near unexpected token `newline'
install.sh: line 8: `<!DOCTYPE html>'

**Comment by aronchanisme** [comment]
fixed 
![image](https://github.com/matrixorigin/mo_ctl_standalone/assets/46433151/7c4b950f-36a1-41e7-a34e-faab249bd941)

**Comment by dengn** [comment]
still the same in my ubuntu environment.

<img width="552" alt="企业微信截图_bc62db6a-ffd4-4471-99f4-bf0724ca66ab" src="https://github.com/matrixorigin/mo_ctl_standalone/assets/4965857/0cc67eee-6f82-4bc0-a6ca-3789fae0c29f">

**Comment by aronchanisme** [comment]
fixed, reason: to download a file from github, will need to change `github.com` to `raw.githubusercontent.com` in the URL
https://www.baidu.com/link?url=9Pl6AyC9NfYaqxZx7zb32e5nLDDVAnPaowqNf9wSztmpuiKnRYCU24gw5vOSstj5VFsmZXMZ3gle7EMf3-LEJB8NyVefefKnTTKAzY6hd5O&wd=&eqid=fbdc7c56000003280000000664a6ce91

**Comment by dengn** [comment]
fixed.
